### ISSUE TITLE
Error with New Screen API

### ISSUE THREAD

**Issue by Harikrishnadhas** [mariodavid/cuba-component-wizard#14] opened 2019-08-01 17:19 UTC
My Entity editor is created using new Screen API. I'm creating a wizard to edit the entity. But I'm getting the below error.

ClassCastException: com.haulmont.cuba.gui.components.AbstractFrame cannot be cast to de.diedavids.cuba.wizard.gui.components.AbstractWizardStep

**Comment by mariodavid** [comment] 2019-08-01 18:57
Hi, can you share some of the code?

An example project would be good as well.


Thanks,
Mario

**Comment by Harikrishnadhas** [comment] 2019-08-02 01:22
I have changed my browser and editor screens to legacy screens and now the Wizard is working fine. I'm in tight schedule of my project hence I will provide you the code in some time.

**Comment by halahot** [comment] 2019-08-29 11:42
Hi, Mario! I have exactly the same problem. Implemented on a test example https://github.com/halahot/wizardExample.

Thanks,
Max

**Comment by innovaringenieria** [comment] 2019-10-14 00:44
Hi, Mario.
I have same mistake
`Caused by: java.lang.ClassCastException: class com.haulmont.cuba.gui.components.AbstractFrame cannot be cast to class de.diedavids.cuba.wizard.gui.components.AbstractWizardStep (com.haulmont.cuba.gui.components.AbstractFrame and de.diedavids.cuba.wizard.gui.components.AbstractWizardStep are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @28486181)
	at de.diedavids.cuba.wizard.web.gui.components.WebWizardStep.getWizardStepInstanceLoadedViaXml(WebWizardStep.java:89) ~[wizard-web-0.5.0.jar:na]
	at de.diedavids.cuba.wizard.web.gui.components.WebWizardStep.getWizardStep(WebWizardStep.java:72) ~[wizard-web-0.5.0.jar:na]
	at de.diedavids.cuba.wizard.web.gui.components.WebWizardStep.onActivate(WebWizardStep.java:44) ~[wizard-web-0.5.0.jar:na]
	at de.diedavids.cuba.wizard.web.gui.components.WebWizard.activateStep(WebWizard.java:169) ~[wizard-web-0.5.0.jar:na]
	at de.diedavids.cuba.wizard.web.gui.components.WebWizard.setCurrentStep(WebWizard.java:163) ~[wizard-web-0.5.0.jar:na]
	at de.diedavids.cuba.wizard.web.gui.components.WebWizard.lambda$createLayout$0(WebWizard.java:142) ~[wizard-web-0.5.0.jar:na]
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170) ~[cuba-global-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:92) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.gui.components.WebTabSheet.fireTabChanged(WebTabSheet.java:600) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.gui.components.WebTabSheet.lambda$initComponentTabChangeListener$ba8aefab$1(WebTabSheet.java:545) ~[cuba-web-7.1.1.jar:7.1.1]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496) ~[vaadin-server-8.6.4-20-cuba.jar:8.6.4-20-cuba]
	... 70 common frames omitted`

**Comment by Harikrishnadhas** [comment] 2019-10-14 18:03
Hi @mariodavid ,

Does this issue resolved? Can I try implementing Wizard in Cuba 7 Screens?

Thanks,
Hari

**Comment by mariodavid** [comment] 2020-08-09 10:19
Hi,

I just released version 0.8.0 which supports CUBA 7 based Screen APIs.

Please try with the new version. I will close this for now.

Cheers
Mario

**Closed as completed by mariodavid** 2020-08-09 10:19 UTC
